### ISSUE TITLE
jobs always abort

### ISSUE THREAD

**Issue by fischejo** [argos-research/genode-Taskloader#5]
A Task with the `period` attribute bigger than 0, starts a job every `period`-time. But every further job is aborted:
```
[init -> taskloader] Trying to start 00.hey but previous instance still running or undestroyed. Abort.
```

Example Task-Set: 
```
<taskset>
    <periodictask>
        <criticaltime>1000</criticaltime>
        <quota>1M</quota>
        <period>2000</period>
        <numberofjobs>0</numberofjobs>
        <pkg>hey</pkg>
        <executiontime>1000</executiontime>
        <priority>10</priority>
        <config></config>
        <id>0</id>
    </periodictask>
</taskset>
```
Note: The default hey blob is used.

### only `push_profile` branch:

When the first job terminates, an `exit` event will be sent. Is this a correct behaviour or should it be sent, when the last job of a task is terminated?

**Comment by BugUser0815** [comment]
The taskloader behaves that way because Robert suggested to move the destruction of tasks to the stop command.
Basically the idea was to destroy the tasks once they finish.
https://github.com/argos-research/genode-Taskloader/blob/20eb20fe9f28bf02f3db11ccd980ff6953047c90/src/taskloader/task.cc#L47
Unfortunately the destruction of a critical exited or force exited child led to the problem that Genode stopped working. So Robert and I moved the destruction.
https://github.com/argos-research/genode-Taskloader/blob/20eb20fe9f28bf02f3db11ccd980ff6953047c90/src/taskloader/taskloader_session_component.cc#L117
Based on this behavior Robert deployed the Jobs periodically himself to avoid Genode crashes.
We haven't found the evil line of code yet, which leads to this behavior.
If you want the taskloader to work the way you describe it you have to use the line of the first link and delete the line of the second link. Otherwise the taskloader works as Robert used it.

Furthermore Genode has no knowledge about jobs. From Genode's point of view every job is a task. Only we know that a task is a job which belongs to a greater task. Consequently it is correct that the taskloader sends profile data every time a "job" exits because it does not know that a task is job.
